version: '2.3'
services:
  postgres:
    image: postgres:9.5.9
    environment:
      - POSTGRES_USER: $POSTGRES_USER
      - POSTGRES_DB: $POSTGRES_DATABASE
      - POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"