# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  release:
    docker:
      - image: circleci/node:12.6.0
    working_directory: ~/src
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get install python-dev
            sudo apt-get install python3-dev
            sudo apt-get install python-pip
            sudo pip install awscli
      - run: npm install
      - run:
          name: 'Creating Test DB'
          command: |
            aws rds create-db-instance --db-name=$POSTGRES_DATABASE \
              --db-instance-identifier=$AWS_DB_INSTANCE_IDENTIFIER \
              --db-instance-class=t2.micro --engine=postgres --engine-version=10 \
              --master-username=$POSTGRES_USER --master-user-password=$POSTGRES_PASSWORD \
              --no-deletion-protection --db-security-groups=$AWS_SECURITY_GROUP --region=$AWS_REGION
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - release