# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  release:
    docker:
      - image: circleci/node:12.6.0
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: 'Installing Postgres'
          command : |
            sudo apt update
            sudo apt install postgresql postgresql-contrib
      - run:
          name: 'Creating Test DB'
          command: |
            sudo -u postgres <<'HERE'
            createdb $POSTGRES_DATABASE
            HERE
      - run: npm install
      - run: npm test
      - run: whoami
workflows:
  version: 2
  build:
    jobs:
      - release