# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  release:
    docker:
      - image: circleci/node:12.6.0
    working_directory: ~/src
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install postgresql postgresql-contrib
      - run: npm install
      - run: npm test
      - run: whoami
workflows:
  version: 2
  build:
    jobs:
      - release