# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  release:
    docker:
      - image: circleci/node:12.6.0
      - image: postgres:9.6-alpine
        name: postgres
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DATABASE
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    working_directory: ~/src
    steps:
      - checkout
      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
      #       chmod +x ~/docker-compose
      #       sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      # - run: docker-compose up -d
      - run: sleep 20
      # - run: docker ps
      # - run: docker exec -d src_postgres_1 pg_ctl -D /var/lib/postgresql/data -l logfile start
      # - run: sleep 10
      - run:
          name: Start Postgres
          command: |
            docker -D -H $DOCKER_HOST info
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - release